version: '3.1'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: pass123!
            POSTGRES_USER: postgres
            POSTGRES_DB: cube
        ports:
            - 5432:5432