version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123!
      MYSQL_DATABASE: qz
      MYSQL_USER: quartz
      MYSQL_PASSWORD: quartz
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db